### ISSUE TITLE
add more gestures!

### ISSUE THREAD

**Issue by Sweeper777** [yenbekbay/AYGestureHelpView#8]
In my app, there a lots of different kinds of gestures, like swiping with two fingers, double tap with two fingers. I wish I can show gestures help for those kind of gestures as well.

My Suggestion:

Create two classes called `Finger` and `FingerMovement`. A `Finger` represents the position of the finger in a tap, long tap, or double tap gesture. A `FingerMovement` represents the movement of a finger in a swipe gesture. It has a start and an end point. In the methods, instead of accepting parameters `startPoint`, `endPoint`, you accept an array of `Finger` or `FingerMovement`. This allows people to show gesture help for multi-finger gestures.

**Comment by yenbekbay** [comment]
@Sweeper777 Sorry, I don't really write any Objective-C these days – and I don't intend to publish any updates to this library in the foreseeable future. Since the codebase for the library is quite small, you would have no problem just copying and modifying it in your project.

**Comment by Sweeper777** [comment]
Okay, I'll consider doing that.
